[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
predictions_dapp = "4Fh9X5RA3NiTe5TRSUXZsR354q2Dt2V9vA7Pu9P5VUb4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/danishiftikhar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
